### ISSUE TITLE
A question, rather than an issue

### ISSUE THREAD

**Issue by eterlova** [rformassspectrometry/MsFeatures#13] opened 2022-03-10 21:54 UTC
Hello all,

I am trying to implement a "pipeline" of xcms preprocessing > MsFeatures grouping > QFeatures to quantify intensity for each group > feature annotation with MetaboAnnotation

Q1: is it an adequate plan?
Q2: am I right that only raw unfilled peaks can be used as input for 'groupFeatures`?
From the tutorial I thought that I can choose the assay, but that results in error:
```
se2 <- groupFeatures(JT2_results, param=SimilarRtimeParam(10), rtime = "rtmed", i=2)
Error in FUN(X[[i]], ...) : unused argument (i = 2)
```
(note same error comes out if I use i=1).

Q3: if the answer to Q2 is yes, does it mean that unfilled intensities go into QFeatures? should I fill in the peaks afterwards manually?

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggfortify_0.4.14            RColorBrewer_1.1-2          magrittr_2.0.2              pheatmap_1.0.12            
 [5] MsFeatures_1.2.0            xcms_3.16.1                 BiocParallel_1.28.3         MSnbase_2.20.4             
 [9] ProtGenerics_1.26.0         mzR_2.28.0                  Rcpp_1.0.8                  ggplot2_3.3.5              
[13] QFeatures_1.4.0             MultiAssayExperiment_1.20.0 SummarizedExperiment_1.24.0 Biobase_2.54.0             
[17] GenomicRanges_1.46.1        GenomeInfoDb_1.30.1         IRanges_2.28.0              S4Vectors_0.32.3           
[21] BiocGenerics_0.40.0         MatrixGenerics_1.6.0        matrixStats_0.61.0         

loaded via a namespace (and not attached):
 [1] tidyr_1.2.0             vsn_3.62.0              foreach_1.5.2           assertthat_0.2.1        BiocManager_1.30.16    
 [6] affy_1.72.0             GenomeInfoDbData_1.2.7  robustbase_0.93-9       impute_1.68.0           pillar_1.7.0           
[11] lattice_0.20-45         glue_1.6.2              limma_3.50.1            digest_0.6.29           XVector_0.34.0         
[16] colorspace_2.0-3        preprocessCore_1.56.0   Matrix_1.4-0            plyr_1.8.6              MALDIquant_1.21        
[21] XML_3.99-0.9            pkgconfig_2.0.3         zlibbioc_1.40.0         purrr_0.3.4             scales_1.1.1           
[26] RANN_2.6.1              affyio_1.64.0           tibble_3.1.6            generics_0.1.2          farver_2.1.0           
[31] AnnotationFilter_1.18.0 ellipsis_0.3.2          withr_2.5.0             lazyeval_0.2.2          MassSpecWavelet_1.60.0 
[36] cli_3.2.0               crayon_1.5.0            ncdf4_1.19              fansi_1.0.2             doParallel_1.0.17      
[41] MASS_7.3-55             tools_4.1.2             lifecycle_1.0.1         stringr_1.4.0           munsell_0.5.0          
[46] cluster_2.1.2           DelayedArray_0.20.0     pcaMethods_1.86.0       compiler_4.1.2          mzID_1.32.0            
[51] rlang_1.0.2             grid_4.1.2              RCurl_1.98-1.6          rstudioapi_0.13         iterators_1.0.14       
[56] MsCoreUtils_1.6.2       igraph_1.2.11           bitops_1.0-7            labeling_0.4.2          gtable_0.3.0           
[61] codetools_0.2-18        DBI_1.1.2               R6_2.5.1                gridExtra_2.3           dplyr_1.0.8            
[66] utf8_1.2.2              clue_0.3-60             stringi_1.7.6           parallel_4.1.2          vctrs_0.3.8            
[71] DEoptimR_1.0-10         tidyselect_1.1.2  
```

**Comment by jorainer** [comment] 2022-03-11 09:22
Hi,

Q1) yes that sounds reasonable - although I have not yet used `QFeatures` in that line. Could be that that is not yet working smoothly, but I might be wrong there.

Q2) hm, that's strange. What type of object is `JT2_results`? Is it a `SummarizedExperiment` (then it should work)? Or a `XCMSnExp` object (then `i` makes no sense, because there is only the feature matrix, but no different assays)?

Q3) Actually, I would do the gap filling with `fillChromPeaks` on the `xcms` result object before you do `groupFeatures` call.

Be aware that you can do the `groupFeatures` on `xmcs` result objects (`XCMSnExp` objects) but also on `SummarizedExperiments` (which you get from an `xcms` result object using the `quantify` function). For the more `xcms` centered approach you find some information [here](http://sneumann.github.io/xcms/articles/LC-MS-feature-grouping.html), while for the feature grouping on a `SummarizedExperiment` the documentation is [here](https://rformassspectrometry.github.io/MsFeatures/articles/MsFeatures.html).

**Comment by eterlova** [comment] 2022-03-11 10:51
Hello!

Thanks for your response! 

`JT2_results` is a `SummarizedExperiment`:
```
> class(JT2_results)
[1] "SummarizedExperiment"
attr(,"package")
[1] "SummarizedExperiment"
```

I found a clumsy work around it by making a `data.frame ` from `assay(JT2_results, "raw_filled")` and the `rowData(JT2_results)`

Best,
Lisa

**Comment by jorainer** [comment] 2022-03-11 10:56
Hmmm, but strange that `i` is then not working with the `SummarizedExperiment` - I'll look into that.

**Comment by jorainer** [comment] 2022-03-11 12:16
While trying to reproduce your error I actually realized what the problem is: parameter `i` is only used/supported for `groupFeatures` using the `AbundanceSimilarityParam`. That one will group based on similar intensities across samples and these intensities are supposed to be stored as one of the `assays` of the `SummarizedExperiment`. Thus, with `i` it is possible to select which assay should be used. You were using the `i` with the `SimilarRtimeParam`, but that one uses only the information in the `rowData` of the `SummarizedExperiment` and does not access the `assays`. That's why you get the error. No need to use `i` with `SimilarRtimeParam`.

Regarding the question: as said, I would run the `fillChromPeaks` step as a last step of the normalization. The only additional option you have from running the feature grouping on the `xcms` result is that you can also use the `EicSimilarityParam` to group features based on similar EIC shapes. All other feature grouping approaches are available also for `SummarizedExperiment`. In the end, feature grouping with `groupFeatures` simply defines the additional column `"feature_group"` in the `SummarizedExperiments` `rowData` (or in the `XCMSnExp` `featureDefinitions`) data frame. To aggregate intensities with `QFeatures` I assume you need to convert to a `SummarizedExperiment` before.

So, I think it should not make a big difference on what object you do the feature grouping. The `XCMSnExp` has an additional grouping approach and additional options but in the end you will want to convert to a `SummarizedExperiment` after you're done (here I'm not sure if also the feature definitions get correctly copied over, but I'll check that).

**Comment by eterlova** [comment] 2022-03-15 22:15
Oh that makes a lot of sense! Thank you for looking into this

**Comment by jorainer** [comment] 2022-03-16 08:29
I'm closing the issue now - feel free to re-open if needed (or open a new one if you run into other problems)

**Closed by jorainer** 2022-03-16 08:29 UTC
